name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: '21'
  MAVEN_OPTS: '--enable-preview -XX:+UseZGC -Xmx2048m'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: Build core module
      run: |
        mvn clean compile \
          -pl ai-review-core \
          -DskipTests \
          -Dmaven.test.skip=true \
          --no-transfer-progress
      env:
        MAVEN_OPTS: ${{ env.MAVEN_OPTS }}

    - name: Package core module
      run: |
        mvn package \
          -pl ai-review-core \
          -DskipTests \
          -Dmaven.test.skip=true \
          --no-transfer-progress
      env:
        MAVEN_OPTS: ${{ env.MAVEN_OPTS }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifacts
        path: ai-review-core/target/*.jar
        retention-days: 30

  code-quality:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: Run code quality checks
      run: |
        mvn verify \
          -pl ai-review-core \
          -DskipTests \
          -Dmaven.test.skip=true \
          --no-transfer-progress
      env:
        MAVEN_OPTS: ${{ env.MAVEN_OPTS }}
      continue-on-error: true

    - name: Upload quality reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: quality-reports
        path: |
          ai-review-core/target/pmd.xml
          ai-review-core/target/spotbugsXml.xml
          ai-review-core/target/site/
        retention-days: 30

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: Build Docker image
      run: |
        mvn clean package \
          -pl ai-review-core \
          -DskipTests \
          -Dmaven.test.skip=true \
          --no-transfer-progress
        
        docker build -t review-code-ai:latest -f ai-review-core/Dockerfile .
        echo "Docker image built successfully"
      env:
        MAVEN_OPTS: ${{ env.MAVEN_OPTS }}